version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0 # Remplacez par la version souhaitée
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_password
      - KEYCLOAK_ADMIN=taha
      - KEYCLOAK_ADMIN_PASSWORD=taha1234
    ports:
      - 8080:8080
    depends_on:
      - db
    command: start-dev

  db:
    image: postgres:15
    container_name: keycloak_db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
